version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    ports:
      - 4444:4444
    restart: always

  store:
    build: .  
    volumes:
      - ./artifacts/feature_errors:/artifacts/feature_errors
    command: ["./wait-for-selenium-container.sh", "behave", "features", "-D", "driver=remote"]
    depends_on:
      - selenium

