version: "3.7"
services: 
  zalenium:
    image: dosel/zalenium
    ports:
      - "4444:4444"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos



