name: Automation CI

on: [ push ]

jobs:
  backend-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Installing libraries
        working-directory: ./Backend
        run: pip install -r requirements.txt
      - name: Launch Pytest
        working-directory: ./Backend
        run: pytest Tests/
